/* O COMANDO SELECT
seleção projeção e junção
*/

SELECT NOW() as DATA_HORA;

SELECT NOW() AS DATA_HORA, 'TALLYTO RODRIGUES' AS ALUNO;

SELECT 'TALLYTO RODRIGUES';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT ENDERECO, SEXO, EMAIL, NOME  FROM CLIENTE;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

-- APENAS PARA FINS ACADEMICOS

SELECT * FROM CLIENTE;

