-- modelagem básica
-- ENTIDADE = TABELA
-- CAMPOS = ATRIBUTOS
CLIENTE - TABELA

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

-- PROCESSOS DE MODELAGEM

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM (WORKBANCH, BRMODELO, VISIO, ETC)

-- FASE 01 e FASE 02 - AD ADM DE DADOS

-- Fase 03 - DBA / AD

MODELAGEM FÍSICA - SCRIPTS DE BANCO
