-- modelagem básica
-- ENTIDADE = TABELA
-- CAMPOS = ATRIBUTOS
CLIENTE - TABELA NOME - CARACTER(30) CPF - NUMERICO(11) EMAIL - CARACTER(30) TELEFONE - CARACTER(30) ENDERECO - CARACTER(100) SEXO - CARACTER(1) -- PROCESSOS DE MODELAGEM
MODELAGEM CONCEITUAL - RASCUNHO MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM (WORKBANCH, BRMODELO, VISIO, ETC) -- FASE 01 e FASE 02 - AD ADM DE DADOS
-- Fase 03 - DBA / AD
MODELAGEM FÍSICA - SCRIPTS DE BANCO -- INICIANDO A MODELAGEM FISICA
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE EXEMPLO;

-- CONECTANDO AO BANCO DE DADOS
USE EXEMPLO;

-- CRIANDO A TABELA CLIENTE
CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

-- VERIFICANDO AS TABELAS
SHOW TABLES;

-- VERIFICANDO A ESTRUTURA DA TABELA
DESCRIBE CLIENTE;

DESC CLIENTE;

-- sintaxe basica de inserção - INSERT INTO TABELA (CAMPOS) VALUES (VALORES)
-- FORMA 01 - Omitindo as colunas
INSERT INTO
    CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES
    (
        'JOAO',
        'M',
        'JOAO@GMAIL.COM',
        '12345678901',
        '999999999',
        'RUA 1, 123'
    );

INSERT INTO
    CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES
    (
        'MARIA',
        'F',
        'MARIA@GMAIL.COM',
        '12345678902',
        '999999998',
        'RUA 2, 123'
    );

INSERT INTO
    CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES
    (
        'JOSE',
        'M',
        'JOSE@GMAIL.COM',
        '12345678903',
        '999999997',
        'RUA 3, 123'
    );