-- modelagem básica
-- ENTIDADE = TABELA
-- CAMPOS = ATRIBUTOS
CLIENTE - TABELA NOME - CARACTER(30) CPF - NUMERICO(11) EMAIL - CARACTER(30) TELEFONE - CARACTER(30) ENDERECO - CARACTER(100) SEXO - CARACTER(1) -- PROCESSOS DE MODELAGEM
MODELAGEM CONCEITUAL - RASCUNHO MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM (WORKBANCH, BRMODELO, VISIO, ETC) -- FASE 01 e FASE 02 - AD ADM DE DADOS
-- Fase 03 - DBA / AD
MODELAGEM FÍSICA - SCRIPTS DE BANCO -- INICIANDO A MODELAGEM FISICA
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE EXEMPLO;

-- CONECTANDO AO BANCO DE DADOS
USE EXEMPLO;

-- CRIANDO A TABELA CLIENTE
CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

-- VERIFICANDO AS TABELAS
SHOW TABLES;

-- VERIFICANDO A ESTRUTURA DA TABELA
DESCRIBE CLIENTE;

DESC CLIENTE;

-- sintaxe basica de inserção - INSERT INTO TABELA (CAMPOS) VALUES (VALORES)
-- FORMA 01 - Omitindo as colunas
INSERT INTO
    CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES
    (
        'JOAO',
        'M',
        'JOAO@GMAIL.COM',
        '12345678901',
        '999999999',
        '233 Sawayn Shoals Apt. 223 - South Jordan, MA / 17573'
    );

INSERT INTO
    CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES
    (
        'MARIA',
        'F',
        'MARIA@GMAIL.COM',
        '12345678902',
        '999999998',
        '26740 Benton Point Apt. 164 - Manchester, VT / 21362'
    );

INSERT INTO
    CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES
    (
        'JOSE',
        'M',
        'JOSE@GMAIL.COM',
        '12345678903',
        '999999997',
        '62861 Jaiden Square Suite 975 - Normal, MO / 98645'
    );

-- FORMA 02 - Informando as colunas

INSERT INTO CLIENTE
    (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES
    ('GUSTAVO', 'M', 'GUSTAVO@GMAIL.COM', '12345678904', '999999996', '829 Cristal Fork Suite 233 - Mankato, AL / 31513');

-- FORMA 03 - INSERT COMPACTO -> SOMENTE MYSQL

INSERT INTO CLIENTE VALUES
    ('GILBERTO', 'M', 'GILBERTO@GMAIL.COM', '12345678905', '999999995', '3562 Bayer Fords Suite 230 - Washington, NM / 86547'),
    ('GABRIELA', 'F', 'GABRIELA@GLOBO.COM', '12345678906', '999999994', '7506 Gerhold Rest Apt. 146 - Anchorage, MD / 60961');
